### ISSUE TITLE
I love the taste of cinnamon toast crunch

### ISSUE THREAD

**Issue by ccocks** [towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch#15]
I love the taste of cinnamon toast crunch

Wait a minute, what?

Actually what I **really** wanted to ask you was If we could implement the Scratch Dark theme that you made in ScratchTools (`STforScratch`)

**Comment by towerofnix** [comment]
We love the taste of cinnamon toast crunch too!!

Sure, go for it! Just be sure to give credits (preferably pointing to our Scratch profile page [_nix](https://scratch.mit.edu/users/_nix/)) somewhere that is visible to users of ScratchTools (e.g. when they go to choose their preferred theme). If you run into any troubles with the CSS not working quite right, you may want to refer to Scratch Addons' implementation of it as we haven't really updated our style synce creating it, and we know SA *has* made sure their editor themes addon keeps working.

**Comment by ccocks** [comment]
Ok thank you.

**Comment by ccocks** [comment]
Where do I get the CSS from?

**Comment by towerofnix** [comment]
We shared our userstyle here! https://github.com/scratchfoundation/scratch-gui/issues/59#issuecomment-455717312

That links to the gist you're looking for: [towerofnix/s3-dark.css](https://gist.github.com/towerofnix/806550f907da63f63f55bb39c99789bf)

ScratchAddons' stylesheet is I think in [experimental_editor.css](https://github.com/ScratchAddons/ScratchAddons/tree/master/addons/editor-dark-mode), mainly. It's a whole lot more detailed than our stylesheet and probably works a lot more reliably LOL, you would just have to fill in the colors they took from from our userstyle (see [addon.json](https://github.com/ScratchAddons/ScratchAddons/blob/3e73c928ba92bc0e10eb7558968ca37d8afec4a4/addons/editor-dark-mode/addon.json#L1202-L1226)).

Also, their code is licensed under [the GPL](https://github.com/ScratchAddons/ScratchAddons/blob/master/LICENSE), which requires code you derive from it to use the GPL too. I don't really know if that's enforceable if you just adapt the parts that help get the CSS to work for you 🤷 But if you're worried (and don't want to just use all their CSS and license your project under GPL), you can just try debugging the editor with inspect element, and add in similar CSS rules as in our stylesheet.

**Comment by ccocks** [comment]
Whats the difference between your file and ScratchAddons' file?

**Comment by towerofnix** [comment]
Ours hasn't been updated for about five years, so it may not work 100% with the current Scratch editor. But, the Scratch editor hasn't been updated very much over the last five years either, so it's probably not that broken.

ScratchAddons' is more up to date and will give more complete coverage. It's coded to support switching between a bunch of color schemes using the same CSS file, though, so they use lots of [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/var) to enable customization. (The addon automatically fills in those variables with the values from addon.json that we linked.)

Our CSS and color scheme aren't formally licensed or anything, but we consider it public for anyone to use and just would like credits. ScratchAddons' code is licensed under the GPL, so you would probably be expected to openly license your project's source code with GPL too, in order to make use of ScratchAddons' code.

**Comment by ccocks** [comment]
Ok thank you. I don't know how this GPL thing works so Ill just use yours. Enjoy your cinnamon toast! 😺

**Comment by ccocks** [comment]
How would you like your credits? Github/Scratch? _nix/nix/towerofnix?

**Comment by towerofnix** [comment]
Thanks! Please use the name _nix and link to our Scratch profile [_nix](https://scratch.mit.edu/users/_nix/). 🎊

**Comment by ccocks** [comment]
Ok
